import { Task, taskType } from "entities/Task";

export const healthTask: Task[] = [
    {
        id: "1",
        favourites: false,
        title: "качалка",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "2",
        favourites: false,
        title: "пробежка",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "3",
        favourites: false,
        title: "прогулка",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "4",
        favourites: false,
        title: "отжимания",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "5",
        favourites: false,
        title: "плавание",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "6",
        favourites: false,
        title: "плавание",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "7",
        favourites: false,
        title: "плавание",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
    {
        id: "8",
        favourites: false,
        title: "плавание",
        done: false,
        type: taskType.TARGET,
        userId: "1",
    },
];
